---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rtweet)
# plotting and pipes - tidyverse!
library(ggplot2)
library(dplyr)
# text mining library
library(tidytext)
library(jsonlite)
## install rtweet from CRAN
library(httr)
library(rtweet)
```

Links I used:

## https://rpubs.com/fitzpatrickm8/yelpapi
## https://github.com/richierocks/yelp


## GOOGLE MAPS

```{r}
library(mapsapi)
maps_key = Sys.getenv("maps_key")
register_google(key = maps_key)
```


```{r}
doc = mp_directions(origin = "Davis", #from UCD Pav
                      destination = "San jose",
                      mode = c("driving", "transit", "walking", "bicycling"),
                      alternatives = FALSE,
                      waypoints = NULL,
                      key = paste(maps_key))
r = mp_get_routes(doc)
```

```{r}
c = data.frame(c("distance",r$distance_text),c("duration",r$duration_text))
names(c) = c("","")
c
```


## TWITTER
```{r}

## search for n tweets using the rstats hashtag
rt <- get_trends(
  "sacramento")

rt %>% select(trend,tweet_volume)
```

## YELP

```{r}


yelp_client_ID = Sys.getenv("yelp_client_ID")
yelp_key = Sys.getenv("yelp_key")

#create token with provided id, key
res <- POST("https://api.yelp.com/oauth2/token",
            body = list(grant_type = "client_credentials",
                        client_id = yelp_client_ID,
                        client_secret = yelp_key))

token <- content(res)$access_token

```


```{r}
yelp <- "https://api.yelp.com"
term <- "cookies"
location <- "Davis, CA"
categories <- NULL
limit <- 50
radius <- 1000
url <- modify_url(yelp, path = c("v3", "businesses", "search"),
                  query = list(term = term, location = location, 
                               limit = limit,
                               radius = radius))
res <- GET(url, add_headers('Authorization' = paste("Bearer", Sys.getenv("yelp_key"))))

results <- content(res,as="text")

yelp_results = data.frame(fromJSON(results))
names(yelp_results) = str_remove(list(names(yelp_results))[[1]],"businesses.")
yelp_results
```


```{r}
leaflet(yelp_results$coordinates) %>% addMarkers() %>% addTiles()

```




```{r}
search_guardian <- function(text, page = 1) {
      r <- GET(
        "https://content.guardianapis.com/search",
        query = list(
          `api-key` = news_key,
          q = text,
          page = page
        )
      )
      stop_for_status(r)
      json <- content(r, as = "text", encoding = "UTF-8")
      fromJSON(json)$response
    }
    
    guard = search_guardian(paste(input$destination), 2)$results
    guard$webUrl = paste0("<a href='",guard$webUrl,"'>",guard$webTitle,"</a>")
    
    response <- guard %>% select(webUrl)
```
```{r}
r = GET(
      "https://api.openweathermap.org/data/2.5/weather",
      query = list(
        appid = Sys.getenv("weather_key"),
        lat = geocode(paste(input$destination))$lat,
        lon = geocode(paste(input$destination))$lon
      ))
    r
    
    stop_for_status(r)
    
    json <- content(r, as = "text")
    data.frame(fromJSON(json)) %>% select(weather.description,
                                          main.feels_like,
                                          main.temp_min,
                                          main.temp_max,
                                          main.pressure,
                                          main.humidity,
                                          wind.speed)
```


